---
# defaults file for allspark

allspark_root_domain: allspark.localhost
allspark_root_directory: /opt/allspark
allspark_admin_user: admin
allspark_country: FR
allspark_state: Haute-Garonne
allspark_location: Toulouse
allspark_organisation: CRE
allspark_common_name: "*.{{ allspark_root_domain }}"
allspark_docker_version: "17.03.2"

allspark_ldap:
  enabled: false
  organization: Allspark
  image: osixia/openldap:1.2.0
  management_image: osixia/phpldapadmin:0.7.1


allspark_monitoring:
  enabled: true

allspark_traefik:
  selfsigned: false
  image: traefik:latest

allspark_portainer:
  image: portainer/portainer:latest

allspark_rocketchat:
  enabled: true
  image: rocket.chat:latest
  database_image: mongo:latest

allspark_prometheus:
  image: prom/prometheus:v2.1.0

allspark_grafana:
  image: grafana/grafana:latest

allspark_node_exporter:
  image: prom/node-exporter

allspark_cadvisor:
  image: google/cadvisor:latest

allspark_gitlab:
  enabled: false
  with_runner: false
  image: gitlab/gitlab-ce:latest
  runner_image: gitlab/gitlab-runner:latest
  lfs_enabled: true

allspark_jenkins:
  enabled: false
  image: jenkins/jenkins
  # Toggle default plugin import from release.
  import_plugins: true

allspark_sonarqube:
  enabled: false
  image: sonarqube:latest

### Release configuration
# Should not be here
allspark_release_tmp_directory: /opt/allspark/release
allspark_release_destination: /opt/allspark.tar.gz


## RHEL7 / CentOS specific system configuration
allspark_epel_repo_file: "/etc/yum.repos.d/epel.repo"
allspark_epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
allspark_epel_gpg_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
