---

- name: Configuration directory
  file:
    state: directory
    path: "{{ allspark_root_directory }}/config/jenkins"

- name: Copy configuration
  copy:
    src: files/
    dest: "{{ allspark_root_directory }}/config/jenkins/"

- name: Generate Jenkins configuration
  template:
    src: templates/configure-email-notification.groovy.j2
    dest: "{{ allspark_root_directory }}/config/jenkins/configure-email-notification.groovy"
  when: allspark_jenkins.enabled

- name: Register admin user
  shell: "cat {{ allspark_root_directory}}/data/secrets/admin_user.txt"
  register: allspark_jenkins_user
  changed_when: false
  tags:
  - skip_ansible_lint

- name: Register admin password
  shell: "cat {{ allspark_root_directory}}/data/secrets/admin_password.txt"
  register: allspark_jenkins_password
  changed_when: false
  tags:
  - skip_ansible_lint

- name: Creating Jenkins volume
  docker_volume:
    name: "allspark_{{ item }}"
  with_items:
    - jenkins_home
    - jenkins_plugins
    - allspark_jenkins_slave

- name: Register docker group UID
  getent:
    database: group
    key: docker

- name: Jenkins master
  docker_container:
    name: jenkins
    image: "{{ downloads.jenkins.image }}:{{ downloads.jenkins.tag }}"
    state: "{{ allspark_jenkins.enabled and 'started' or 'absent'}}"
    purge_networks: true
    networks:
      - name: allspark
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes: >-
      [
        "allspark_jenkins_home:/var/jenkins_home",
        "{{ allspark_root_directory }}/config/jenkins/configure-email-notification.groovy:/usr/share/jenkins/ref/init.groovy.d/configure-email-notification.groovy",
        "{{ allspark_root_directory }}/config/jenkins/master.groovy.d:/usr/share/jenkins/ref/init.groovy.d",
        "allspark_jenkins_plugins:/usr/share/jenkins/ref/plugins",
        "{{ allspark_root_directory}}/data/secrets/admin_password.txt:/run/secrets/jenkins-pass",
        "{{ allspark_root_directory}}/data/secrets/admin_user.txt:/run/secrets/jenkins-user"
      ]
    labels:
      "heritage": "allspark"
    restart_policy: always

- name: Jenkins slave
  docker_container:
    name: jenkins_slave
    image: "{{ downloads.jenkins_slave.image }}:{{ downloads.jenkins_slave.tag }}"
    state: "{{ allspark_jenkins.enabled and 'started' or 'absent'}}"
    user: "jenkins:{{ getent_group.docker[1] }}"
    purge_networks: true
    networks:
      - name: allspark
    env:
      JENKINS_URL: "http://jenkins:8080"
      JENKINS_TUNNEL: "jenkins:9489"
      JENKINS_AGENT_NAME: docker_slave
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent
      JENKINS_USER: "{{ allspark_jenkins_user.stdout }}"
      JENKINS_PASSWORD: "{{ allspark_jenkins_password.stdout }}"
    volumes: >-
      [
        {% if jenkins_docker_socket_mount %}
        "/var/run/docker.sock:/var/run/docker.sock",
        {% endif %}
        "allspark_jenkins_slave:/home/jenkins/agent",
        "{{ allspark_root_directory }}/config/jenkins/slave_init.sh:/slave_init.sh"
      ]
    command: /slave_init.sh
    entrypoint: /bin/sh
    labels:
      "heritage": "allspark"
    restart_policy: always
