# Images
gitlab_image: gitlab/gitlab-ce
rocketchat_image: rocket.chat
rocketchat_mongodb_image: mongo
haproxy_image: haproxy
haproxy_exporter_image: quay.io/prometheus/haproxy-exporter
grafana_image: grafana/grafana
prometheus_image: prom/prometheus
cadvisor_image: google/cadvisor
node_exporter_image: prom/node-exporter
sonarqube_image: sonarqube
portainer_image: portainer/portainer
openldap_image: osixia/openldap
phpldapadmin_image: osixia/phpldapadmin
gitlab_runner_image: gitlab/gitlab-runner
jenkins_image: jenkins/jenkins
centos_image: centos
volumerize_image: blacklabelops/volumerize
mattermost_image: mattermost/mattermost-prod-app
mattermost_postgresql_image: postgres

# Tags
gitlab_tag: latest
rocketchat_tag: latest
rocketchat_mongodb_tag: latest
# Alpine tag is required, because it bundle rsyslogd
# which allow us to read logs from HAProxy
haproxy_tag: alpine
haproxy_exporter_tag: v0.9.0
grafana_tag: latest
prometheus_tag: v2.1.0
cadvisor_tag: latest
node_exporter_tag: latest
sonarqube_tag: latest
portainer_tag: latest
openldap_tag: 1.2.0
phpldapadmin_tag: 0.7.1
gitlab_runner_tag: latest
jenkins_tag: latest
centos_tag: 7
volumerize_tag: latest
mattermost_tag: latest
mattermost_postgresql_tag: latest

# Downloads
downloads:
  cadvisor:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_tag }}"
  centos:
    enabled: true
    image: "{{ centos_image }}"
    tag: "{{ centos_tag }}"
  gitlab:
    enabled: "{{ allspark_gitlab.enabled }}"
    image: "{{ gitlab_image }}"
    tag: "{{ gitlab_tag }}"
  gitlab_runner:
    enabled: "{{ allspark_gitlab.with_runner }}"
    image: "{{ gitlab_runner_image }}"
    tag: "{{ gitlab_runner_tag }}"
  grafana:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ grafana_image }}"
    tag: "{{ grafana_tag }}"
  jenkins:
    enabled: "{{ allspark_jenkins.enabled }}"
    image: "{{ jenkins_image }}"
    tag: "{{ jenkins_tag }}"
  node_exporter:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ node_exporter_image }}"
    tag: "{{ node_exporter_tag }}"
  openldap:
    enabled: "{{ allspark_ldap.enabled }}"
    image: "{{ openldap_image }}"
    tag: "{{ openldap_tag }}"
  phpldapadmin:
    enabled: "{{ allspark_ldap.enabled }}"
    image: "{{ phpldapadmin_image }}"
    tag: "{{ phpldapadmin_tag }}"
  portainer:
    enabled: true
    image: "{{ portainer_image }}"
    tag: "{{ portainer_tag }}"
  prometheus:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ prometheus_image }}"
    tag: "{{ prometheus_tag }}"
  rocketchat:
    enabled: "{{ allspark_rocketchat.enabled }}"
    image: "{{ rocketchat_image }}"
    tag: "{{ rocketchat_tag }}"
  rocketchat_mongodb:
    enabled: "{{ allspark_rocketchat.enabled }}"
    image: "{{ rocketchat_mongodb_image }}"
    tag: "{{ rocketchat_mongodb_tag }}"
  sonarqube:
    enabled: "{{ allspark_sonarqube.enabled }}"
    image: "{{ sonarqube_image }}"
    tag: "{{ sonarqube_tag }}"
  haproxy:
    enabled: true
    image: "{{ haproxy_image }}"
    tag: "{{ haproxy_tag }}"
  haproxy_exporter:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ haproxy_exporter_image }}"
    tag: "{{ haproxy_exporter_tag }}"
  volumerize:
    enabled: true
    image: "{{ volumerize_image }}"
    tag: "{{ volumerize_tag }}"
  mattermost:
    enabled: "{{ allspark_mattermost.enabled }}"
    image: "{{ mattermost_image }}"
    tag: "{{ mattermost_tag }}"
  mattermost_postgresql:
    enabled: "{{ allspark_mattermost.enabled }}"
    image: "{{ mattermost_postgresql_image }}"
    tag: "{{ mattermost_postgresql_tag }}"

# Misc

## Set this to true to force the download of every images, even if they are
## disabled in the configuration
force_download: false
